// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpcbjwmdgqrvzgahuobs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwY2Jqd21kZ3FydnpnYWh1b2JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNTc1ODUsImV4cCI6MjA3MTczMzU4NX0.iELg5xu7VjR90bY7h7EEJe4xaoS3iYz598nWhXkOv9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});